# Analisis de los datos de la encuesta Jumping Girls

In [1]:
import pandas as pd

In [2]:
encuesta_ESP = "Encuesta Digital Girls_SP&ENG_A.xlsx"

In [4]:
df = pd.read_excel(encuesta_ESP)
df.head()

,Label,Dibujar o pintar,Inventar historias,"Actuar, bailar y cantar",Contruir cosas con bloques,Hacer experimentos o jugar con química,"Observar insectos, plantas o estrellas",Hacer manualidades,Hacer preguntas sobre comó funcionan las cosas,Hacer deporte,...,Jugar con animales,Jugar con ordenadores o videojuegos,Resolver acertijos,Aprender sobre el cuerpo humano,Hacer cosas en equipo,Estar solo,Jugar a ser profesores,Asignatura1,Asignatura1.1,Personalidad
0,NEGOCIOS Y FINANZAS,2,1,1,3,1,1,3,2,1,...,1,1,3,3,3,1,3,matemáticas,idiomas,Organizador
1,NEGOCIOS Y FINANZAS,3,3,3,2,2,1,3,2,2,...,1,2,1,1,3,1,3,lengua,arte y dibujo,Social
2,NEGOCIOS Y FINANZAS,1,1,1,1,3,2,2,3,3,...,1,2,2,2,3,1,3,matemáticas,educación física,Realista
3,NEGOCIOS Y FINANZAS,1,2,1,3,2,1,1,3,3,...,2,2,2,1,3,2,2,matemáticas,ciencias,Organizador
4,NEGOCIOS Y FINANZAS,3,2,1,2,1,1,1,2,3,...,1,2,3,2,3,1,2,historia,arte y dibujo,Social

In [7]:
print("Tenemos ", df['Label'].count(), "respuestas de la encuesta en Español")

Tenemos  356 respuestas de la encuesta en Español

In [8]:
# por categorias profesionales
df['Label'].value_counts()

NEGOCIOS Y FINANZAS                     106
TEGNOLOGIA E INFORMATICA                 62
SALUD Y MEDICINA                         43
DERECHO Y CIENCIAS SOCIALES              35
INGENIERIA Y CONSTRUCCION                32
EDUCACIÓN Y FORMACIÓN                    25
COMUNICACIÓN Y MEDIOS                    25
CREATIVAS Y ARTISTICAS                   13
CIENCIAS CIENTIFICAS E INVESTIGACION      8
NATURALEZA Y MEDIO AMBIENTE               7
Name: Label, dtype: int64

In [11]:
encuesta_ENG = 'Encuesta Digital Girls_SoloENG_A.xlsx'
df_ENG = pd.read_excel(encuesta_ENG)
df_ENG.head()

,Label,Dibujar o pintar,Inventar historias,"Actuar, bailar y cantar",Contruir cosas con bloques,Hacer experimentos o jugar con química,"Observar insectos, plantas o estrellas",Hacer manualidades,Hacer preguntas sobre comó funcionan las cosas,Hacer deporte,...,Resolver acertijos,Aprender sobre el cuerpo humano,Hacer cosas en equipo,Estar solo,Jugar a ser profesores,Asignatura1,Asignatura2,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,BUSINESS AND FINANCE,3,1,1,3,1,1,3,3,1,...,3,2,1,2,3,matemáticas,idiomas,"maths, other languages",Investigador,Investigator: I like to analyze things careful...
1,LAW AND SOCIAL SCIENCE,3,3,2,1,1,1,3,1,2,...,2,2,2,1,3,idiomas,arte y dibujo,"other languages, arts and drawing",Social,Social: what I like most is engaging with peop...
2,HEALTH AND MEDICINE,3,3,1,2,2,1,2,1,3,...,2,3,3,1,2,ciencias,arte y dibujo,"science, arts and drawing",Investigador,Investigator: I like to analyze things careful...
3,LAW AND SOCIAL SCIENCE,1,2,1,1,1,2,1,3,1,...,3,1,3,1,1,historia,literatura,"history, literature",Investigador,Investigator: I like to analyze things careful...
4,BUSINESS AND FINANCE,1,2,1,3,2,3,2,3,3,...,3,1,3,3,1,matemáticas,educación física,"maths, physical education",Emprendedor,Entrepeneur: I enjoy starting new things with ...

In [13]:
print("Tenemos ", df_ENG['Label'].count(), "respuestas de la encuesta en Inglés")

Tenemos  131 respuestas de la encuesta en Inglés

In [12]:
# por categorias profesionales
df_ENG['Label'].value_counts()

BUSINESS AND FINANCE        106
LAW AND SOCIAL SCIENCE       10
TECHNOLOGY AND COMPUTING      6
HEALTH AND MEDICINE           4
COMMUNICATIONS AND MEDIA      2
CREATIVE AND ARTISTIC         2
EDUCATION AND TRAINING        1
Name: Label, dtype: int64

# Problemas

## 1. En ambas encuestas hay una profesión que es mucho mas numerosa que las demás.

## 2. Para algunas profesiones ("NATURALEZA Y MEDIO AMBIENTE" y otras) hay muy pocos ejemplos.