In [1]:
import pandas as pd

In [2]:
nombre_archivo = "personalidad_ENG_traducida.txt"
df = pd.read_csv(nombre_archivo, header=None, names=['Personalidad', 'Desc'], sep=':')

In [3]:
df.head()

   Personalidad                                               Desc
0  Investigador   I like to analyze things carefully before mak...
1        Social   what I like most is engaging with people and ...
2  Investigador   I like to analyze things carefully before mak...
3  Investigador   I like to analyze things carefully before mak...
4   Emprendedor   I enjoy starting new things with others or al...

In [4]:
lista1 = df['Personalidad'].tolist()
#lista2 = df['Asignatura2'].tolist()

In [5]:
for i in range(len(lista1)):
    print(lista1[i].strip())

Investigador
Social
Investigador
Investigador
Emprendedor
Organizador
Artístico
Investigador
Manos a la obra
Investigador
Social
Organizador
Investigador
Social
Organizador
Investigador
Organizador
Social
Organizador
Investigador
Investigador
Organizador
Investigador
Organizador
Emprendedor
Organizador
Emprendedor
Social
Investigador
Investigador
Investigador
Organizador
Manos a la obra
Manos a la obra
Investigador
Organizador
Organizador
Manos a la obra
Manos a la obra
Organizador
Investigador
Organizador
Manos a la obra
Manos a la obra
Artístico
Investigador
Investigador
Emprendedor
Manos a la obra
Investigador
Organizador
Social
Manos a la obra
Emprendedor
Investigador
Emprendedor
Emprendedor
Social
Organizador
Manos a la obra
Organizador
Investigador
Manos a la obra
Manos a la obra
Organizador
Manos a la obra
Artístico
Manos a la obra
Manos a la obra
Manos a la obra
Manos a la obra
Manos a la obra
Emprendedor
Manos a la obra
Organizador
Investigador
Emprendedor
Manos a la obra
Organizador
Manos a la obra
Social
Manos a la obra
Investigador
Investigador
Manos a la obra
Manos a la obra
Manos a la obra
Organizador
Investigador
Manos a la obra
Investigador
Emprendedor
Investigador
Emprendedor
Organizador
Organizador
Emprendedor
Social
Organizador
Social
Emprendedor
Organizador
Investigador
Organizador
Manos a la obra
Artístico
Manos a la obra
Manos a la obra
Investigador
Social
Investigador
Organizador
Investigador
Manos a la obra
Manos a la obra
Investigador
Investigador
Investigador
Investigador
Manos a la obra
Investigador
Manos a la obra
Organizador
Investigador
Social
Organizador
Investigador
Investigador
Emprendedor
Investigador
Manos a la obra

In [ ]:
def leer_archivo_y_generar_listas(nombre_archivo):
    """
    Lee un archivo de texto con dos strings separados por comas y genera dos listas.

    Args:
        nombre_archivo (str): La ruta del archivo de texto.

    Returns:
        tuple: Dos listas con los datos del archivo.
    """

    try:
        # Leer el archivo de texto con Pandas
        df = pd.read_csv(nombre_archivo, header=None, names=['Asignatura1', 'Asignatura2'])

        # Convertir las columnas en listas
        lista1 = df['columna1'].tolist()
        lista2 = df['columna2'].tolist()

        return lista1, lista2

    except FileNotFoundError:
        print(f"Error: El archivo '{nombre_archivo}' no fue encontrado.")
        return [], []
    except Exception as e:
        print(f"Ocurrió un error inesperado: {e}")
        return [], []

In [ ]:
# Ejemplo de uso
nombre_archivo = "asignaturas.txt"  # Reemplaza con el nombre de tu archivo

#Generar un fichero de ejemplo si no existe.
try:
    with open(nombre_archivo, 'x') as f:
        f.write('valor1,valor2\nvalor3,valor4\nvalor5,valor6')
except FileExistsError:
    print('El fichero ya existe')

lista1, lista2 = leer_archivo_y_generar_listas(nombre_archivo)

if lista1 and lista2:
    print("Lista 1:", lista1)
    print("Lista 2:", lista2)